import { Inter } from 'next/font/google'
import './style/globals.css'
import Navbar from './components/Navbar'
import Footer from './components/Footer'

// Notez que la déclaration de la police Inter ne devrait pas être utilisée ici.
// Vous pouvez la déclarer dans votre fichier CSS global.

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
      </head>
      <body>
        <Navbar />
        {children}
        <Footer/>
      </body>
    </html>
  )
}
